name: License Scanning

on:
  push:
    branches: [ main ]

jobs:
  fossa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - name: Add GOPATH to GITHUB_ENV
        run: echo "GOPATH=$(go env GOPATH)" >>"$GITHUB_ENV"

      - name: Add GOPATH to GITHUB_PATH
        run: echo "$GOPATH/bin" >>"$GITHUB_PATH"

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{secrets.FOSSA_TOKEN}}