name: Test

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test-health-lib:
    name: test-health-lib
    runs-on: ubuntu-latest
    steps:
      - name: Set up most recent version of Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Generate coverage report
        run: go test `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella

  test-checks-lib:
    name: test-checks-lib
    runs-on: ubuntu-latest
    steps:
      - name: Set up most recent version of Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Start test environment
        working-directory: checks
        run: docker-compose -f checks/docker-compose.yaml up -d

      - name: Run tests
        working-directory: checks
        run: go test ./...
